spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: amrit
    password: amrit
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081